
platform :ios, '10.0'
# source "https://code.aliyun.com/mpaas-public/podspecs.git"
target 'MPFrameworkDemo_plugin' do
pod 'mPaas',:path => 'Third/mPaas/'
# 监控
    pod 'matrix-wechat',:path => 'Third/matrix-master/'
    pod 'FBRetainCycleDetector',:path => 'Third/FBRetainCycleDetector-master/'
    pod 'YYDebugDatabase',:path => 'Third/iOSDebugDatabase-master/'
    pod 'DoraemonKit', :subspecs => ['Core','WithLogger','WithMLeaksFinder','WithDatabase'],  :path => 'Third/DoraemonKit-master/'
# Sarted
    pod 'SnapKit',:path => 'Third/SnapKit-develop/'
    pod 'CollectionKit',:path => 'Third/CollectionKit-master/'
    pod 'Hero',:path => 'Third/Hero-master/'
    pod 'YetAnotherAnimationLibrary',:path => 'Third/YetAnotherAnimationLibrary-master/'
    
#Learn
    pod 'Alamofire',:path => 'Third/Alamofire-master/'
    pod 'Kingfisher',:path => 'Third/Kingfisher-master/'
    pod 'SwiftyJSON',:path => 'Third/SwiftyJSON-master/'
    pod 'Charts',:path => 'Third/Charts-master/'

end

