#source 'https://github.com/CocoaPods/Specs.git'
 
platform :ios, "10.0"
use_frameworks!

target 'Ink_Swift' do


pod 'AFNetworking'
pod 'SnapKit', '~> 3.0.2'
pod 'HandyJSON', '~> 4.2.0-beta1' 
pod 'SwiftyJSON'
pod 'SVProgressHUD'
pod 'Toast-Swift', '~> 2.0.0'
pod 'IQKeyboardManagerSwift'
pod 'Kingfisher', '~> 3.0'
pod 'SwiftDate'
pod 'MJRefresh'
pod 'BadgeSwift', '~> 4.0'
 

end
