# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ink_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ink_Swift

  pod 'RAMAnimatedTabBarController', "~> 2.0.13"   
  pod 'ReactiveCocoa', '~> 5.0.0'
  pod 'SnapKit', '~> 3.2.0'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'IQKeyboardManagerSwift'
  pod 'Material', '~> 2.0'
  pod 'IBAnimatable'
  pod 'Kingfisher', '~> 3.0'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'SwiftyJSON'
 
  pod 'Moya/ReactiveSwift'
  pod 'XLPagerTabStrip', '~> 7.0'
  pod "TextFieldEffects"
  pod 'SwifterSwift'
  pod 'ImagePicker'
  pod 'LCActionSheet'
  pod 'Dollar', '6.1.0'
  pod 'Cent', '6.0.3'
  pod 'KeychainAccess', '3.0.1'
  pod 'UIColor_Hex_Swift', '~> 3.0.2'
 
  pod 'RxBlocking', '~> 3.0'
  pod 'XCGLogger', '4.0.0'
  
  pod 'BSImagePicker', '~> 2.5.0'
  pod 'TSVoiceConverter', '0.1.3'
  pod 'XLActionController'
  pod 'TimedSilver', '1.0.0'

  #Objective-C
  pod 'YYText', '1.0.7'
  pod 'SVProgressHUD', '2.0.4'
  pod 'INTULocationManager', '4.2.0'


end
